[server]
host = "127.0.0.1"
port = 4500
public_dir = "public/www"
enable_ssl = true
cert_file = "certs/server.crt"
key_file = "certs/server.key"

[proxy]
enable = 1
prefix = "/proxy/"
target_ip = "127.0.0.1"
target_port = 8000

[logging]
log_file = "logs/server.log"

[features]
auto_index = true